### ISSUE TITLE
Planet Rotation

### ISSUE THREAD

**Issue by OwenProto** [Karth42/SimpleKeplerOrbits#5] opened 2019-03-28 22:17 UTC
I don't see planet rotation functionality in this project. It seems that the velocity handle transform must be a child of the orbiting body to work correctly. When rotating the planet it also rotates the velocity handle and causes the orbit to change wildly. Is there a solution to this somewhere already in the project?

**Comment by Karth42** [comment] 2019-03-30 17:53
Hi.
Please provide more information for problem reproduction. How do you get wildly changing orbit?

Velocity handle object should be child of orbiting body. But if it's not child, then it should work too, as long as nothing more moving this handle at same tame (for example, another orbiting body). Anyway, this handle object is designed for quick setup of orbits by hands, and if you want, you can delete them and setup orbits by script. They are optional. Check out example scenes in project.

**Comment by OwenProto** [comment] 2019-03-30 18:04
The issue was that since the velocity handle is a child of the orbiting body, if I wanted to also rotate the body with another script like this for example:
`transform.rotation *= Quaternion.Euler(new Vector3(0, 1 * rotationSpeed * Time.deltaTime, 0));`
the velocity handle would also be rotated about the moving body causing the orbit to behave unexpectedly.

I simply modified the scripts by replacing the velocity handle transform with a Vector3 that could be edited in the inspector. This solved the orbit issue and still allows for easy setup without scripting. It also gets rid of an extra empty transform in the hierarchy.

**Comment by Karth42** [comment] 2019-03-30 18:42
I misunderstood word 'rotate', because people often use it to describe revolution around attractor (I don't know why).
For your usecase I recommend not to rotate orbiting body itself and also never attach any visual components to it. Instead just create another child for this, which will be view layer of celestial body.
Hierarchy layout example:
--Body (KeplerOrbitMover)
----BodyView (MeshRenderer or SpriteRenderer)
------Collider (Optional)
----VelocityHandle
In this example you just need to rotate or scale only BodyView object. This is common layout for any usable-as-prefab object, not only in context of orbits (when visual component not attachet to root object, where controller component exist).
If you don't need this hierarchy changes, you could also solve this without changing scripts by deletion of VelocityHandle reference, or enabling bool property "LockOrbitEditing".

**Comment by Karth42** [comment] 2019-03-30 18:51
For your information, this plugins contains only basic implementation of velocity handle, which is not using editor gizmos tools extensions and other fancy technics.
To make it work, KeplerOrbitMover need to do two things: 1) apply orbit state velocity to VelocityHandle transform, 2) in opposite direction - read and apply velocityHandle transform to orbit state velocity.
this two operations are executed in Update loop. LockOrbitEditing disables one of update direction - from transform to orbit state, and makes VelocityHandle unusable as handle, but usable as visual indicator, because it will keep updating from orbit state.

**Comment by OwenProto** [comment] 2019-03-30 19:03
Yes, I should have mentioned that I considered this solution - which would work - however for my specific needs and in order to interface with my project without duplicating components etc. all the translations/rotations must be on the same object. Considering I had to modify the scripts to interface with my system, further modifications don’t introduce any disadvantages and the simple Vector3 variable solution seems to work perfectly.

Thanks for sharing this project and for your guidance!

**Closed** 2019-03-30 20:20 UTC
Labels: question
